### ISSUE TITLE
Profile picture helper

### ISSUE THREAD

**Issue by sabuto** [redbeed/OpenOverlay#13]
Add a helper to retrieve the profile picture on twitch for the user.

**Comment by chris-redbeed** [comment]
As I already said I like this idea of small helpers.
I will try to add some, that will handle all the requests and cases to get same information about a user.

**Comment by chris-redbeed** [comment]
I created a function in the `UsersClient` where you can get the User data of a user by name or id.
Example:
``` php
$client = new UsersClient();
$users = $client->byUsername('movrs');
```
